### ISSUE TITLE
cypress-image-snapshot gitlab-ci integration

### ISSUE THREAD

**Issue by qvrsefv5** [simonsmith/cypress-image-snapshot#71]
hello, is there way to integrated cypress-image-snapshot to gitlab-ci?
i want to generate base image every night at eg. 3:00
and then i want to run test every hour that will compare base image to current run
i tried gitlab cache, dependencies and needs but i could get it work any help would be greatly appreciated 
here is my gitlab-ci

```
stages:
  # - test_base
  - test

# test_base:
#   image: cypress/browsers:node-20.14.0-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1
#   stage: test_base
#   script:
#     # install dependencies
#     - npm i
#     # run Cypress tests
#     - npx cypress run --browser chrome --env updateSnapshots=true
#   only:
#     variables:
#       - $SCHEDULE_NIGHTLY_VARIABLE_X
#   artifacts:
#     when: always
#     paths:
#       - cypress/snapshots/signIn.spec.cy.ts/**/*.png
#     expire_in: 1 day
#   cache:
#     key: "$CI_COMMIT_REF_SLUG" # The cache key, typically based on branch or commit
#     paths:
#       - cypress/

test:
  image: cypress/browsers:node-20.14.0-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1
  stage: test
  script:
    # install dependencies
    - npm i
    # run Cypress tests
    - npx cypress run --browser chrome
  only:
    variables:
      - $SCHEDULE_VARIABLE_X
  # cache:
  #   key: "$CI_COMMIT_REF_SLUG"
  # dependencies:
  #   - test_base
  # needs:
  # - job: test_base
  #   artifacts: true
  artifacts:
    when: always
    paths:
      - cypress/reports/mocha/**/*.html
      - cypress/screenshots/**/*.png
      - cypress/snapshots/signIn.spec.cy.ts/__diff_output__/*.png
    expire_in: 2 hours
```

**Comment by simonsmith** [comment]
Hey,

It's absolutely possible to run this plugin via Gitlab, that is how I run all the tests across several projects. Unfotunately this repository is not the right place to seek help with configuring GitLab

Try:

* https://forum.gitlab.com/ 
* https://docs.gitlab.com/
* https://docs.cypress.io/app/continuous-integration/gitlab-ci

**Comment by qvrsefv5** [comment]
Here is how i solve it with generic repository
```
stages:
  - test

test_base:
  image: cypress/browsers:node-22.14.0-chrome-133.0.6943.53-1-ff-135.0-edge-133.0.3065.59-1
  # image:
  #   name: cypress/included:cypress-14.0.0-node-22.13.1-chrome-132.0.6834.83-1-ff-134.0.2-edge-132.0.2957.115-1
  #   entrypoint: [""]
  stage: test
  script:
    # curl packages and get package_id
    # install jq
    - apt update && apt install -y jq
    - apt install -y curl
    - |
      PACKAGE_ID="$(curl --header "JOB-TOKEN: $CI_JOB_TOKEN" \
               "https://gitlab.company.com/api/v4/projects/46/packages" | jq '.[0] | .id')"
    - echo "PACKAGE_ID $PACKAGE_ID"
    # remove package
    - |
      curl --request DELETE --header "JOB-TOKEN: $CI_JOB_TOKEN" \
               "https://gitlab.company.com/api/v4/projects/46/packages/$PACKAGE_ID"
    # install dependencies
    - npm i
    # run Cypress tests
    - npx cypress run --browser chrome
    - ls
    - ls cypress/snapshots/
    - ls cypress/snapshots/bla_signIn.spec.cy.ts
    - |
      for file in ./cypress/snapshots/bla_signIn.spec.cy.ts/*; do
        if [ -f "$file" ]; then
          filename=$(basename "$file")
          echo "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/base_image/1.0.0/$filename"
          curl --header "JOB-TOKEN: $CI_JOB_TOKEN" \
               --upload-file "$file" \
               "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/base_image/1.0.0/$filename"
          echo "Uploaded: $filename"
        fi
      done
  only:
    variables:
      - $SCHEDULE_NIGHTLY_VARIABLE_X
  artifacts:
    when: always
    paths:
      - cypress/screenshots/**/*.png
      - cypress/videos/**/*.mp4
    expire_in: 1 day

test:
  image: cypress/browsers:node-22.14.0-chrome-133.0.6943.53-1-ff-135.0-edge-133.0.3065.59-1
  stage: test
  script:
    - apt update && apt install -y curl
    - |
      FILES=("HomePage375x667.snap.png" "HomePage768x1024.snap.png" "HomePage1440x900.snap.png")
      for file in "${FILES[@]}"; do
        curl --location --header  "JOB-TOKEN: $CI_JOB_TOKEN" \
             --output "$file" \
             --create-dirs \
             "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/base_image/1.0.0/$file"
        echo "Downloaded: $file"
      done
    - ls
    - mkdir ./cypress/snapshots/
    - mkdir ./cypress/snapshots/bla_signIn.spec.cy.ts/
    - mv HomePage375x667.snap.png HomePage768x1024.snap.png HomePage1440x900.snap.png cypress/snapshots/bla_signIn.spec.cy.ts/
    - ls
    - ls cypress/snapshots/bla_signIn.spec.cy.ts
    # install dependencies
    - npm i
    # run Cypress tests
    - npx cypress run --browser chrome
  only:
    variables:
      - $SCHEDULE_VARIABLE_X
  artifacts:
    when: always
    paths:
      - cypress/reports/mocha/**/*.html
      - cypress/screenshots/**/*.png
      - cypress/snapshots/**/*.png
    expire_in: 2 hours
```
